= クラスタリソースのクォータ
:experimental:

[WARNING]
====
続ける前に、LDAPの演習(「外部認証プロバイダ(LDAP)の設定」)を終了して下さい。
====

== 演習の概要


前の演習では、*Project* にクォータを適用する方法を見ました。デフォルトのクォータを設定したので、誰かが新しい *Project* をリクエストしたときにはいつでもデフォルトのクォータが割り当てられます。このような *Project* クォータは、クラスタ内のリソースを制御するのに最適です。

しかし、クォータを個々の *Project* ではなく、クラスタ全体に適用したい場合はどうでしょうか？

---

### ユースケース

*Project* ベースの `quota` の代わりに `clusterresourcequota` を使用する主なユースケースは2つあります。そのうちの一つは、特定のユーザにクォータを設定したい場合です。これは、ユーザに必要なだけの *Project* を作成させたい場合に便利(これによりマルチテナンシーを実現します)で、ユーザが消費できるリソースの量を制限したいケースです。

もう一つのユースケースは、アプリケーションごとにクォータを設定したい場合です。この場合、アプリケーションスタックは複数のOpenShift *Project* にまたがっている可能性があります。

この演習では、両方のユースケースを調査します。

#### ユーザーごとのクォータの設定

`clusterresourcequota` をユーザに設定するには、`kubeadmin` である必要があります。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

では、`normaluser1` にクォータを設定します。`openshift.io/requester=` の `annotation` キーを使用して、これらのクォータが適用される *Project* を特定します。この演習では、10個より多くの *Pod* を作成することを禁止するハードクォータを設定します。

[source,bash,role="execute"]
----
oc create clusterquota for-user-normaluser1 \
    --project-annotation-selector openshift.io/requester=normaluser1 \
    --hard pods=10
----

[NOTE]
====
構文は `openshift.io/requester=<username>` です。
====

設定を表示します。

[source,bash,role="execute"]
----
oc get clusterresourcequotas for-user-normaluser1 -o yaml
----

設定は以下のようになっているはずです。

[source,yaml]
----
apiVersion: quota.openshift.io/v1
kind: ClusterResourceQuota
metadata:
  creationTimestamp: "2019-11-22T01:29:06Z"
  generation: 1
  name: for-user-normaluser1
  resourceVersion: "73824"
  selfLink: /apis/quota.openshift.io/v1/clusterresourcequotas/for-user-normaluser1
  uid: 79764862-0cc7-11ea-bba7-0640f541f946
spec:
  quota:
    hard:
      pods: "10"
  selector:
    annotations:
      openshift.io/requester: normaluser1
----

ユーザ `normaluser1` は、作成したすべての *Project* で10個以下の *Pod* を作成することができます。これはこのユーザが作成した *Project* (`openshift.io/requester: normaluser1` annotationに基づく) にのみ適用され、ユーザがアクセスできるプロジェクトには適用されません。これについては後ほど説明します。

では `normaluser1` でログインしてみましょう。

[source,bash,role="execute"]
----
oc login -u normaluser1 -p Op#nSh1ft
----

現在の *Project* をリストアップします。

[source,bash,role="execute"]
----
oc get projects
----

このユーザは *Project* を持っていないはずなので、このような出力が表示されるはずです。(もし持っていても気にしなくて大丈夫です)

----
No resources found.
----

`welcome1` と `welcome2` の2つの *Project* を作成します。

[source,bash,role="execute"]
----
oc new-project welcome1
oc new-project welcome2
----

次に二つのアプリケーションを作成します。1つは `welcome1` *Project* に作り、もう1つは `welcome2` *Project* に作ります.

[source,bash,role="execute"]
----
oc new-app -n welcome1 --name=php1 quay.io/redhatworkshops/welcome-php:latest
oc new-app -n welcome2 --name=php2 quay.io/redhatworkshops/welcome-php:latest
----

デプロイが終わると、それぞれのNamespaceに1つずつ、2つの実行中の *Pod* ができるはずです。`oc get pods` コマンドで確認してください。(出力が表示されるまでに何度か実行しなければならないかもしれません)

[source,bash,role="execute"]
----
oc get pods -n welcome1 -l deploymentconfig=php1
oc get pods -n welcome2 -l deploymentconfig=php2
----

出力は以下のようになっているはずです。

----
[~] $ oc get pods -n welcome1 -l deploymentconfig=php1
NAME           READY   STATUS    RESTARTS   AGE
php1-1-nww4m   1/1     Running   0          4m20s
[~] $ oc get pods -n welcome2 -l deploymentconfig=php2
NAME           READY   STATUS    RESTARTS   AGE
php2-1-ljw9w   1/1     Running   0          4m20s
----

これで `kubeadmin` になってクォータを確認してみましょう。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

`oc describe clusterresourcequotas for-user-normaluser1` を実行してクォータの状態を確認します。

[source,bash,role="execute"]
----
oc describe clusterresourcequotas for-user-normaluser1
----

以下のような出力が表示されます。

----
Name:		for-user-normaluser1
Created:	22 minutes ago
Labels:		<none>
Annotations:	<none>
Namespace Selector: ["welcome1" "welcome2"]
Label Selector: 
AnnotationSelector: map[openshift.io/requester:normaluser1]
Resource	Used	Hard
--------	----	----
pods		2	10
----

10個中2個の *Pod* が使用されていることと、クォータが適用されているNamespaceが確認できます。`welcome1` のNamespaceをチェックして、クォータが見張るannotationを確認してください。

[source,bash,role="execute"]
----
oc get ns welcome1 -o yaml
----

出力は以下のようになるはずです。特にannotationに注意してください。

[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: normaluser1
    openshift.io/sa.scc.mcs: s0:c26,c20
    openshift.io/sa.scc.supplemental-groups: 1000690000/10000
    openshift.io/sa.scc.uid-range: 1000690000/10000
  creationTimestamp: "2019-11-22T01:40:10Z"
  name: welcome1
  resourceVersion: "76604"
  selfLink: /api/v1/namespaces/welcome1
  uid: 058b7e91-0cc9-11ea-8361-0a190b75e8c6
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
----

それでは `normaluser1` になって、10個を超える *Pod* にスケールしてみます。

[source,bash,role="execute"]
----
oc login -u normaluser1 -p Op#nSh1ft
oc scale dc/php1 -n welcome1 --replicas=5
oc scale dc/php2 -n welcome2 --replicas=6
----

実行中の *Pod* の数に注意して見てみましょう。

[source,bash,role="execute"]
----
oc get pods --no-headers -n welcome1 -l deploymentconfig=php1 | wc -l
oc get pods --no-headers -n welcome2 -l deploymentconfig=php2 | wc -l
----

これらのコマンドはどちらも、合計で10個以上の *Pod* を返しません。イベントをチェックして、クオータが動作しているのを確認してください。

[source,bash,role="execute"]
----
oc get events -n welcome1 | grep "Error creating" | head -1
oc get events -n welcome2 | grep "Error creating" | head -1
----

以下のようなメッセージが表示されるはずです。

----
3m31s       Warning   FailedCreate                  replicationcontroller/php2-1   Error creating: pods "php2-1-wn22s" is forbidden: exceeded quota: for-user-normaluser1, requested: pods=1, used: pods=10, limited: pods=10
----

ステータスを確認するには、`kubeadmin` になって先程の `describe` コマンドを実行します。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
oc describe clusterresourcequotas for-user-normaluser1
----

 *Pod* のハードクォータの上限に達したことが確認できます。

----
Name:		for-user-normaluser1
Created:	45 minutes ago
Labels:		<none>
Annotations:	<none>
Namespace Selector: ["welcome1" "welcome2"]
Label Selector: 
AnnotationSelector: map[openshift.io/requester:normaluser1]
Resource	Used	Hard
--------	----	----
pods		10	10
----

#### Labelによるクォータ
複数の *Project* にまたがる可能性のあるアプリケーションスタックでクォータを設定するには、Labelを使って *Project* を識別する必要があります。まず、`kubeadmin` でログインします。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

Labelに基づいてクォータを設定します。この演習では *Project* を識別するために `appstack=pricelist` のLabelを使用します。

[source,bash,role="execute"]
----
oc create clusterresourcequota for-pricelist \
    --project-label-selector=appstack=pricelist \
    --hard=pods=5
----

ここで2つの *Project* を作成します。

[source,bash,role="execute"]
----
oc adm new-project pricelist-frontend
oc adm new-project pricelist-backend
----

2つの *Project* のユーザ `normaluser1` に `edit` ロールを割り当てます。

[source,bash,role="execute"]
----
oc adm policy add-role-to-user edit normaluser1 -n pricelist-frontend
oc adm policy add-role-to-user edit normaluser1 -n pricelist-backend
----

これら2つの *Project* が `pricelist` アプリケーションスタックに属するものであることを識別するには、対応するNamespaceにLabelを付ける必要があります。

[source,bash,role="execute"]
----
oc label ns pricelist-frontend appstack=pricelist
oc label ns pricelist-backend appstack=pricelist
----

`oc describe clusterresourcequotas` で `for-pricelist` を指定します。

[source,bash,role="execute"]
----
oc describe clusterresourcequotas for-pricelist
----

両方の *Project* がトラッキングされていることがわかるはずです。

----
Name:		for-pricelist
Created:	6 minutes ago
Labels:		<none>
Annotations:	<none>
Namespace Selector: ["pricelist-frontend" "pricelist-backend"]
Label Selector: appstack=pricelist
AnnotationSelector: map[]
Resource	Used	Hard
--------	----	----
pods		0	5
----

`normaluser1` でログインし、それぞれの *Project* にアプリケーションを作成します。

[source,bash,role="execute"]
----
oc login -u normaluser1 -p Op#nSh1ft
oc new-app -n pricelist-frontend --name frontend quay.io/redhatworkshops/pricelist:frontend
oc new-app -n pricelist-backend --name backend quay.io/redhatworkshops/pricelist:backend
----

`kubeadmin` でログインし、`describe` コマンドを実行して、クォータの状態を確認してください。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
oc describe clusterresourcequotas for-pricelist
----

5つの *Pod* クォータに対して2つが使用されていることを確認できます。

----
Name:		for-pricelist
Created:	21 minutes ago
Labels:		<none>
Annotations:	<none>
Namespace Selector: ["pricelist-frontend" "pricelist-backend"]
Label Selector: appstack=pricelist
AnnotationSelector: map[]
Resource	Used	Hard
--------	----	----
pods		2	5
----

[NOTE]
====
`normaluser1` は、`kubeadmin` によって `pricelist-frontend` と `pricelist-backend` のユーザとして割り当てられているため、より多くの *Pod* を作成することができます。`normaluser1` は *Pod* を作成していないので、`openshift.io/requester=normaluser1` annotationはありません。あなたの環境に合わせてクォータポリシーをミックスしたり、マッチさせたりすることができることがわかります。
====

`normaluser1` でログインして、合計5つの *Pod* を超えてアプリケーションをスケールしてみてください。

[source,bash,role="execute"]
----
oc login -u normaluser1 -p Op#nSh1ft
oc scale -n pricelist-frontend dc/frontend --replicas=3
oc scale -n pricelist-backend dc/backend --replicas=3
----

先ほどと同じように、スケールできないというエラーが表示されるはずです。

[source,bash,role="execute"]
----
oc get events -n pricelist-frontend | grep "Error creating" | head -1
oc get events -n pricelist-backend | grep "Error creating" | head -1
----

出力は先の演習と同じようになっているはずです。

----
2m51s       Warning   FailedCreate                  replicationcontroller/backend-1   Error creating: pods "backend-1-r78gk" is forbidden: exceeded quota: for-pricelist, requested: pods=1, used: pods=5, limited: pods=5
----

#### クリーンアップ

`kubeadmin` で行った作業をクリーンアップします。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----

これらのクォータは他の演習と干渉する可能性があるので、この演習で作成した `clusterresourcequota` の両方を削除してください。

[source,bash,role="execute"]
----
oc delete clusterresourcequotas for-pricelist for-user-normaluser1
----

また、この演習で作成した *Project* も削除してください。

[source,bash,role="execute"]
----
oc delete projects pricelist-backend pricelist-frontend welcome1 welcome2
----

次の演習では必ず `kubeadmin` でログインしてください。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }}
----
