## ラボ環境の概要
{{ENVIRONMENT}}で稼働するOpenShift 4クラスタを使って操作します。このラボでは、Rook/CephをベースにしたOpenShift Container Storageのインストールも行います。

事前にOpenShift 4のインストールは完了しています。OpenShiftクラスタは基本的にすべてデフォルトに設定されており、以下のようになっています。

* 3 マスターノード
* 3 ワーカーノード
* 1 踏み台ホスト

link:https://github.com/openshift-labs/workshop-dashboard[Homeroom] はラボのガイド、ターミナル、およびWebコンソールを統合して提供するソリューションです。これは実際には、あなたが利用するOpenShiftクラスタ内で実行されています。

## はじめる前に
これらの演習を通して、様々なコードとコマンドブロックを見ることができます。いくつかのコマンドブロックは直接実行することができます。他のものは実行前にコマンドの修正が必要です。赤い枠線（下記参照）が付いたコマンドブロックが表示されている場合、そのコマンドはクリップボードにコピーされ、少しの修正が必要です。

コマンドブロックの横にあるアイコンは、コマンドが実行されるか、コピーされるかを示しています。

- このコマンドブロックは修正するためにクリップボードにコピーされます。

[source,none,role="copypaste copypaste-warning"]
----
some command to modify
----
[NOTE]
====
コピーしたコマンドを貼り付けるには、次のようにします。

- Cmd + V _macOS上のChromeで動作確認済_
- Ctrl + Shift + V _Windows10上のChromeとFirefoxで動作確認済_
- ターミナルウィンドウで 右クリック + 貼り付け _Windows10 Edgeで動作確認済_
====

- これはコンソールで実行されます

[source,none,role="execute"]
----
echo Hello World\!
----

ほとんどのコマンドブロックは、自動のハイライトやクリックによる実行をサポートしています。上のコマンドブロックの上にカーソルを置いて左クリックすると、自動的にすべてのテキストがハイライトされてコピーしやすくなります。ブロックの横にあるアイコンを見て、それがコピーされるか実行されるかを確認してください。

### cluster-adminの認証
このラボガイドにアクセスするために提供されたログインは、実際にはあなたが利用するターミナルやWebコンソールとは何の関係もありません。私たちは `ServiceAccounts` と呼ばれるKubernetesの機能を使用しており、これは人間ではないユーザーアカウントです。ターミナルとWebコンソールのタブは、これらの `ServiceAccounts` の1つを使用してOpenShift APIと対話しており、そのアカウントには _cluster-admin_ `ClusterRole` が与えられています。これにより、ターミナルとWebコンソールはAPIに対して管理者/特権ユーザのアクションを実行することができます。

OpenShiftの特権(Privileges)は、このワークショップの演習の1つで学習する、一連のロール、ポリシー、およびバインディングによって制御されます。

簡単な例として、次のように実行して `Role` とは何かを詳しく知ることができます。

[source,bash,role="execute"]
----
oc explain Role
----

`ClusterRole` は `Role` と何が違うのかを調べられます。

[source,bash,role="execute"]
----
oc explain ClusterRole
----

以下を実行することで、`RoleBinding` が何かを知ることができます。

[source,bash,role="execute"]
----
oc explain RoleBinding
----

`ClusterRoleBinding` は `RoleBinding` と何が違うのか調べられます。

[source,bash,role="execute"]
----
oc explain ClusterRoleBinding
----

様々なオブジェクトが何であるかについては、常に `oc explain [RESOURCE]` を使用して詳細な説明を得ることができます。

_cluster-admin_ `ClusterRole` で定義されているPolicyRulesを見てみましょう。

[source,bash,role="execute"]
----
oc get clusterrole cluster-admin -o yaml
----

ルールの下で、_cluster-admin_ ロールを持つアカウントは、`resources` とapiGroupの全ての `verbs`、および `nonResourceURLs` の全ての `verbs` にワイルドカード `*` でアクセスできることに注意して下さい。

`verbs` とは、リソースに対して実行するアクションのことです。OpenShiftでは `delete` や `get` などが `verbs` となります。

特定の `verbs` について詳しく知るには、`oc [verb] --help`
を実行します。

例えば、`verbs` の1つである _whoami_ について学んでみましょう。

[source,bash,role="execute"]
----
oc whoami --help
----

現在どんなアカウントを使っているかを確認するために、`oc whoami` を実行してみます。

[source,bash,role="execute"]
----
oc whoami
----

_cluster-admin_ `ServiceAccount` に `ClusterRole` を付与する、_dashboard-cluster-admin_ `ClusterRoleBinding` を調べて見ます。

[source,bash,role="execute"]
----
oc get clusterrolebinding dashboard-cluster-admin -o yaml
----

`ServiceAccount` はこの `ClusterRoleBinding` の `subjects` であり、参照されるロールが _cluster-admin_ `ClusterRole` であることに注目して下さい。

演習全体を通して、cluster-adminは、先に述べたようにクラスタを使って何でもできるようになるので注意して下さい。