= MachineSets, Machines, Nodes
:experimental:

== 演習の概要
Kubernetes `Node` はコンテナがオーケストレーションされ、`Pod` として実行される場所です。OpenShift 4は、`Operator` を使った自動化に重点を置いている点で、OpenShift 3とは根本的に異なります。`Node` に関しては、`Node` の作成と破壊を含め、クラスタサイズの状態を維持することに重点を置いた `Operator` とコントローラのセットがあります。

この演習では、クラスタサイズを保つために利用される `Machineset` と `Machine` について学びます。

---

### MachineSets と Machines
アプリケーション管理の演習で見たように、`ReplicaSet`/`ReplicationController` とそれが作成する `Pod` の間には基本的な関係があります。同様に、`MachineSet` と `Machine` の間にも関係があります。

`MachineSet` は、`Machine` オブジェクトのセットに対して希望する状態を定義します。IPIインストールを使用する場合、`Operator` の仕事は、各 `Machine` の基礎となるインスタンスが実際に存在することを確認し、最終的に各 `Machine` が `Node` になることを確認することです。

以下を実行します。

[source,bash,role="execute"]
----
oc get machineset -n openshift-machine-api
----

以下のように表示されます。

----
NAME                                         DESIRED   CURRENT   READY   AVAILABLE   AGE
cluster-q5kr6-w97nj-worker-ap-southeast-1a   1         1         1       1           103m
cluster-q5kr6-w97nj-worker-ap-southeast-1b   1         1         1       1           103m
cluster-q5kr6-w97nj-worker-ap-southeast-1c   0         0                             103m
----

OpenShiftがインストールされると、インストーラはクラウドプロバイダーに問い合わせて、利用可能なAZを得ます(この環境はAWS上にあるため)。そして、最終的に各AZの `MachineSet` を作成し、希望する `Machine` の数に達するまで、それらのセットを順番にスケーリングします。デフォルトのインストールには2つのWorkerがいるので、最初の2つのAZにはそれぞれ1つのWorkerが作られます。残りのAZは0です。

※演習で使用する環境によっては、`Node` の数が異なる場合があります。

[source,bash,role="execute"]
----
oc get machine -n openshift-machine-api
----

以下のように表示されます。

----
NAME                                               PHASE     TYPE          REGION           ZONE
    AGE
cluster-q5kr6-w97nj-master-0                       Running   m5a.xlarge    ap-southeast-1   ap-southeast-1a   103m
cluster-q5kr6-w97nj-master-1                       Running   m5a.xlarge    ap-southeast-1   ap-southeast-1b   103m
cluster-q5kr6-w97nj-master-2                       Running   m5a.xlarge    ap-southeast-1   ap-southeast-1c   103m
cluster-q5kr6-w97nj-worker-ap-southeast-1a-c7k5k   Running   m5a.4xlarge   ap-southeast-1   ap-southeast-1a   97m
cluster-q5kr6-w97nj-worker-ap-southeast-1b-w8p4d   Running   m5a.4xlarge   ap-southeast-1   ap-southeast-1b   97m
----


[Warning]
====
現在、Masterの `Machines` は保護されていません。クラスタを壊す可能性があるので、誤って、または意図的に削除しないでください。修復は可能ですが、楽しいものではありません。
====

最後に以下を実行します。

[source,bash,role="execute"]
----
oc get nodes
----

以下のように表示されます。

----
NAME                                              STATUS   ROLES                  AGE    VERSION
ip-10-0-135-241.ap-southeast-1.compute.internal   Ready    worker                 96m    v1.25.14+20cda61
ip-10-0-142-79.ap-southeast-1.compute.internal    Ready    control-plane,master   106m   v1.25.14+20cda61
ip-10-0-160-234.ap-southeast-1.compute.internal   Ready    worker                 96m    v1.25.14+20cda61
ip-10-0-171-226.ap-southeast-1.compute.internal   Ready    control-plane,master   106m   v1.25.14+20cda61
ip-10-0-205-200.ap-southeast-1.compute.internal   Ready    control-plane,master   106m   v1.25.14+20cda61
----

各 `Machine` は、それぞれ `Node` に対応しています。IPIでは、Machine OperatorがEC2インスタンスを作成し、次にCoreOS内のIgnitionがOperatorから最初の命令を受け取る、bootstrapのプロセスが走ります。その結果、EC2インスタンスがOpenShift Nodeとして設定され、クラスタに参加することになります。

`oc describe` で様々な `Machine` オブジェクト、`Node` オブジェクトを調べれば、どれがどれと相関しているのかが分かるでしょう。

### クラスタのスケーリング
`Operator` の「魔法」と、それを使った `Machine` と `Node` の管理のおかげで、OpenShift 4でのクラスタのスケーリングは非常に簡単に行えます。

もう一度、`MachineSet` のリストを見てみましょう。

[source,bash,role="execute"]
----
oc get machineset -n openshift-machine-api
----

そのリストの中で、`MachineSet` のひとつを  oc scaleコマンドでスケールしてみましょう。あなたの `MachineSet` の名前はラボガイドの名前とは異なる可能性があるので、特に注意してください。

[source,bash,role="execute"]
----
CLUSTERNAME=$(oc get  infrastructures.config.openshift.io cluster  -o jsonpath='{.status.infrastructureName}')
ZONENAME=$(oc get nodes -L topology.kubernetes.io/zone  --no-headers  | awk '{print $NF}' | tail -1)
oc scale machineset ${CLUSTERNAME}-worker-${ZONENAME} -n openshift-machine-api --replicas=2
----

`MachineSet` が正常にスケーリングされたというメモが表示されているはずです。次に、`Machine` のリストを見てみましょう。

[source,bash,role="execute"]
----
oc get machines -n openshift-machine-api
----

おそらく、`PHASE` が `Provisioning` となっている2つの新しいエントリがすでに存在していると思います。しばらくすると、以下のように表示されます。
※1つのエントリしか存在しない場合もあります

----
cluster-q5kr6-w97nj-worker-ap-southeast-1c-h444j   Provisioning   m5a.4xlarge   ap-southeast-1   ap-southeast-1c   4m51s
cluster-q5kr6-w97nj-worker-ap-southeast-1c-h9xt9   Provisioning   m5a.4xlarge   ap-southeast-1   ap-southeast-1c   4m51s
----

この時点では、バックグラウンドでは自動的にbootstrap処理が行われています。数分後(5分程度)の出力を見てみましょう。

[source,bash,role="execute"]
----
oc get nodes
----

`age` が非常に若いノードが見つかるはずです。
※1つのエントリしか存在しない場合もあります

----
ip-10-0-207-34.ap-southeast-1.compute.internal    Ready    worker                 79s    v1.25.14+20cda61
ip-10-0-216-253.ap-southeast-1.compute.internal   Ready    worker                 83s    v1.25.14+20cda61
----

[Note]
====
`Machine` が準備され、`Node` として追加されるまでには数分かかることがあります。
====

続ける前に、先程スケールアップした `MachineSet` を2から1にスケールダウンしてください。エントリーがひとつしかない場合は、以下の操作は不要です。

${CLUSTERNAME}と${ZONENAME}変数が、数ステップ前のスケールアップ時に設定されていることを確認してください。

[source,bash,role="execute"]
----
oc scale machineset ${CLUSTERNAME}-worker-${ZONENAME} -n openshift-machine-api --replicas=1
----

