= 演習1: Red Hat OpenShift 4 Ops ハンズオン

== 演習概要
本演習は、演習1: Red Hat OpenShift 4 Ops ハンズオンです。 +
本ハンズオンは2つのLabがあり、以下を学びます。

* OpenShift4クラスターへのログインと動作確認
* コンテナイメージのビルドとデプロイ
* Operatorの導入
* Operatorとアプリケーションの連携
* Custom Resourceの設定
* Operatorに対するCLI操作

== Lab1
事前に構築したOpenShift4クラスターを使用して、OpenShift4コンソールやコマンドを使用してクラスターの動作確認を行います。 +
また，OpenShift4クラスターに対するコンテナイメージのビルドやデプロイ操作をOpenShift4の機能を使用して行います。

作業は以下の手順どおりに進めます。

=== Lab1-1: link:ocp4ws-ops-1-1.adoc[OpenShift4クラスターへのログインと動作確認]

=== Lab1-2: link:ocp4ws-ops-1-1.adoc[コンテナイメージのビルド&デプロイ]


== Lab2
JBoss EAPのアプリケーションを立ち上げ、Prometheus JMX ExporterからJMXメトリクスを収集します。 +
また、OpenShift4クラスターに付随しているOperatorHubから、Prometheus Operatorを活用して、JMXメトリクスの情報を可視化するなど、アプリケーションの監視の基礎を学びます。

作業は以下の手順どおりに進めます。

==== Lab2-1: link:ocp4ws-ops-2-1.adoc[Prometheus JMX Exporterの展開]
==== Lab2-2: link:ocp4ws-ops-2-2.adoc[Prometheus Operatorの展開]
==== Lab2-3: link:ocp4ws-ops-2-3.adoc[CustomResourceの設定]

== ハンズオン環境

本ハンズオンでは，OpenShift 4のクラスターを動作環境として使用します。今回は構築済みのクラスター環境ををひとり1クラスター（6台構成+踏台）ずつ使用します。
クラスター環境の詳細と使い方については、 link:environment.adoc[演習環境の概要]を参照下さい。

OpenShift4クラスターに対するCLI操作をを行う際は，クライアントPCから，踏み台サーバー(Bastion Server)にSSH接続し，*ocコマンド* を使って制御します。 +
`+クライントPC <--SSH--> 踏み台サーバー <--oc--> OpenShift4クラスター+`

踏み台サーバーへのSSHログインは、以下のコマンドで行えます。

[source,bash,role="execute"]
----
ssh -l {{ SSH_USERNAME }} {{ BASTION_FQDN }} -o ServerAliveInterval=120
----

あなたの ssh パスワードはこれです。

[source,bash,role="copypaste"]
----
{{ SSH_PASSWORD }}
----

踏み台サーバーでOpenShift 4クラスタにログインする場合は、以下のコマンドで行えます。

[source,bash,role="execute"]
----
oc login -u kubeadmin -p {{ KUBEADMIN_PASSWORD }} {{ API_URL }} 
----